### ISSUE TITLE
Variable not found for indexes error

### ISSUE THREAD

**Issue by BajczA475** [dirkschumacher/ompr#398] opened 2022-01-27 14:47 UTC
Hi, 

When going to set an objective for my model, I get the following error:

```R
#Get and install and turn on all required packages as needed.

list.of.packages = c("pacman", "dplyr", "ROI", "ompr", "ompr.roi", "slam", "Rsymphony",
                     "ROI.plugin.symphony", "tidyr", "lattice")
new.packages = list.of.packages[!(list.of.packages %in% installed.packages()[,"Package"])]
if (length(new.packages) > 0) {
  r=getOption("repos")
  r["CRAN"] = "http://cran.rstudio.com/"
  options(repos=r)
  install.packages(new.packages)
}
pacman::p_load(dplyr, ROI, ompr, ompr.roi, slam, Rsymphony, ROI.plugin.symphony, tidyr, lattice)

#Read in the necessary pre-generated data.
n.ij = readRDS(file="nij1.rds")
B = 10
 
#Read in the relevant boater matrix
boats.n.ij = readRDS(file="boatsnij1.rds")
boatsSTM = as.simple_triplet_matrix(boats.n.ij)
 
#Initialize Bob's model prior to the objective.
start_time <- Sys.time() #Get a start time.
Bobs.mod = MIPModel() %>% 
  add_variable(u[i, j], type = "binary", i = 1:n.ij, j = 1:n.ij) %>%
  add_variable(x[i], type = "binary", i = 1:n.ij) %>% 
  add_variable(y[j], type = "binary", j = 1:n.ij) %>% 
  add_constraint(x[i] == y[j], i = 1:n.ij, j = 1:n.ij, i == j) %>% 
  add_constraint(sum_over(x[i], i = 1:n.ij) <= B) %>% 
  add_constraint(u[i,j] <= x[i] + y[j], i = 1:n.ij, j = 1:n.ij, i != j)
end_time <- Sys.time() #Get an end time.
print(end_time - start_time)
# Time difference of 21.30543 hours

save(Bobs.mod, file = "Bobs_mod")
#load("Bobs.mod")
kleng = length(boatsSTM$i)

#Now, set objective with this specific boats.n.ij file.
start_time <- Sys.time() #Get a start time.
Bobs.mod.full = Bobs.mod %>% set_objective(sum_over(u[boatsSTM$i[k], boatsSTM$j[k]] * boatsSTM$v[k], k = 1:kleng))
# Error: Variable not found for indexes
# Backtrace:
#      █
#   1. ├─`%>%`(...)
#   2. ├─ompr::set_objective(...)
#   3. ├─ompr:::set_objective.linear_optimization_model(...)
#   4. │ └─ompr:::eval_in_model(model, get_expr(expression), caller_env())
#   5. │   └─rlang::eval_bare(...)
#   6. ├─ompr::sum_over(...)
#   7. │ └─listcomp::gen_list(!!enquo(.expr), !!!enquos(...), .env = parent.frame())
#   8. │   └─rlang::eval_bare(code, env = new_environment(parent = .env))
#   9. ├─u[boatsSTM$i[k], boatsSTM$j[k]]
#  10. └─u[boatsSTM$i[k], boatsSTM$j[k]]
# Execution halted
```
Googling this error doesn't produce any hits and what's weirder is that this error doesn't occur when I use a toy/smaller example with the same structure, so does it have something to do with the size of my objects? n.ij is about 8000 and boats.n.ij has 62980096 cells but is very sparse, such that kleng is only about 408000. Let me know if having access to my data files would be valuable.

**Comment by dirkschumacher** [comment] 2022-01-27 16:05
Thanks for taking the time to report that.

The error occurs if you access a variable by index and the indexes are out of bounds. E.g:

``` r
library(ompr)
MIPModel() |> 
  add_variable(x[i], i = 1:3) |> 
  set_objective(x[4])
#> Error: Variable not found for indexes
```

So in the objective function you have a combination of indexes that were not covered by the `add_variable` call. That might also explain why this did not happen with a smaller model.

Ideally for bug repots, it is great to have a [minimal, reproducible example](https://github.com/tidyverse/reprex) where I do not need to load external data (which I won't do).

Also: it takes 20 hours to create the variables? `u[i,j]` seems to have 64 million instances. Are these all needed? Because you can do stuff like `add_variable(u[i, j], type = "binary", i = 1:n.ij, j = 1:n.ij, i < j)` if that makes sense. I might need to work a bit on the speed for these very large models.

**Comment by BajczA475** [comment] 2022-01-27 16:39
Hi, Thanks for taking the time to consider this--it helped me ID the problem. n.ij was only 7934 but u needed to be 7936x7936. I figured it was something dumb on my end. I would have provided an example (I did try to make one) but I couldn't figure out how to replicate the error with one, unfortunately. In the future, though, I would provide one. 

Yeah, u[i,j] and boats.n.ij are seemingly unavoidably large matrices. boats.n.ij is a directed adjacency matrix holding the numbers of boats (we think) are moving between pairs of lakes within a state every year. There are a lot of lakes and a lot of boat movements, although the matrix is still quite sparse. However, I think your suggestion asks if we could consider just the upper or lower triangle and the answer is unfortunately no because the network is directed, so the two triangles above and below the diagonal are not symmetrical. More about the work is here: https://link.springer.com/article/10.1007%2Fs10530-021-02620-6. Basically, we have fit this model in CPLEX before but want an open-source option and ompr works great when I reduce the size of the problem, but we ultimately want a solution to the whole problem, and that has been harder.

A solution should look like plaid pattern (see attached)
![Screenshot 2022-01-27 103412](https://user-images.githubusercontent.com/15620636/151403183-786530a9-54ad-4cf3-95c9-900fdc354ae8.png)
. Because lake i is row i (as donor of boats) and column i (as receiver of boats), selecting a lake means accounting for boats both coming in and out simultaneously. So, we want to mark up to B lakes (rows and columns i) such that we max the corresponding boats counts in boats.nij. I have suspected there *could* be a more streamlined way of achieving the same result, perhaps by converting u to some kind of edge list like boats.n.ij now is, or by using filters as you suggest, but I must not be that clever!

**Comment by dirkschumacher** [comment] 2022-01-27 16:47
Interesting. Thanks! So most of the time spent is creating so called S4 objects. I might need to investigate if we can do that faster using S3. Added an issue for that: #399

**Comment by dirkschumacher** [comment] 2022-01-29 12:03
Seems like a factor of 10 faster.

**Comment by dirkschumacher** [comment] 2022-01-29 12:38
Cool. So, motivated by trying to generate 60 million variables, I improved the code a bit and it `ompr` is now about 10x faster. You can try it if you do `remotes::install_github("dirkschumacher/ompr")`.

I also looked at the paper and I have two observations/questions:

* As far as I can tell, constraint (2) is actually just a precomputed parameter, right? A bit confusing at first, I would have expected it to be defined somewhere else, not under "subject to". Cause otherwise it makes the impression that the model is actually not linear, quadratic.
* If not all lakes are connect (which I assume, as you said the matrix is sparse), then you can generate only those ij pairs that actually are part of the matrix (where n_ij > 0). You can do this like this 👇

```R
MIPModel() |> 
  add_variable(x[i], type = "binary", i = 1:Nij) |>
  add_variable(u[i, j], type = "binary", i = 1:Nij, j = 1:Nij, n[i, j] > 0) |> 
  set_objective(sum_over(n[i, j] * u[i, j], i = 1:Nij, j = 1:Nij, n[i, j] > 0), "max") |>
  add_constraint(u[i, j] <= (x[i] + x[j]) * b[i, j], i = 1:Nij, j = 1:Nij, n[i, j] > 0) |>
  add_constraint(sum_over(x[i], i = 1:Nij) <= B)
```

Depending on the number of 0s in b_ij, one could also set upper bounds for u_ij instead of a constraint, which _might_ make things faster.

```R
MIPModel() |> 
  add_variable(x[i], type = "binary", i = 1:Nij) |>
  add_variable(u[i, j], type = "binary", i = 1:Nij, j = 1:Nij, n[i, j] > 0) |> 
  set_objective(sum_over(n[i, j] * u[i, j], i = 1:Nij, j = 1:Nij, n[i, j] > 0), "max") |>
  set_bounds(u[i, j] == 0, i = 1:Nij, j = 1:Nij, n[i, j] > 0, b[i, j] == 0)
  add_constraint(u[i, j] <= (x[i] + x[j]) * b[i, j], i = 1:Nij, j = 1:Nij, n[i, j] > 0, b[i, j] > 0) |>
  add_constraint(sum_over(x[i], i = 1:Nij) <= B)
```

Disclaimer: I haven't run the R code, but that should in theory work.

**Comment by BajczA475** [comment] 2022-01-31 13:40
Hi! Thanks for the update on the package--I will download and try it out right now. Second, I should have linked this in sooner but I was concerned I was being a bother: https://stackoverflow.com/questions/70276554/in-the-ompr-package-in-r-how-can-i-rephrase-my-objective-constraints-variables. There, you can find some code that produces something sort of like the real problem I'm dealing with, if you want to try it out. There, I note exactly what you had caught--b_ij needn't be included. One could just go into boats_n_ij and clip out all lakes that don't receive nor send a single boat that could spread an infestation (essentially what b_ij is tracking). That's actually exactly what I did here, so my code doesn't include b_ij for that reason. That reduced boats_n_ij from about 9500 x 9500 to about 7950 x 7950, which is pretty significant. However, much of boats_n_ij remains sparse even despite that. I had considered the possibility that smart utilization of bounds/constraints with filters in them could make things easier and faster, but I hadn't come up with anything that felt game-changing--I think your idea for the upper bound here could be especially worth trying, so I think I'll give it a go and see what happens!

**Comment by dirkschumacher** [comment] 2022-01-31 13:51
In https://github.com/dirkschumacher/ompr/discussions/406, @sbmack investigated a bit the performance of large sparse models. This identified a memory issue in the package {listcomp}, which handles all the quantifier/filter logic. The current [GitHub version](https://github.com/dirkschumacher/listcomp) speeds things up significantly I think.

I took the model from SO and ran it 👇
``` r
library(Matrix)
library(slam)
library(dplyr)
#> 
#> Attaching package: 'dplyr'
#> The following objects are masked from 'package:stats':
#> 
#>     filter, lag
#> The following objects are masked from 'package:base':
#> 
#>     intersect, setdiff, setequal, union
library(tidyr)
#> 
#> Attaching package: 'tidyr'
#> The following objects are masked from 'package:Matrix':
#> 
#>     expand, pack, unpack
library(ROI)
#> ROI: R Optimization Infrastructure
#> Registered solver plugins: nlminb, alabama, glpk, lpsolve, quadprog.
#> Default solver: auto.
library(ompr)
library(ompr.roi)
library(Rglpk)
#> Using the GLPK callable library version 4.65
library(ROI.plugin.glpk)
library(lattice)

set.seed(101)
N = 500
boats = rpois(N*N, 2)
keep = sample(c(0,1), N*N, replace=T, prob = c(0.97, 0.03))
boat.dat = boats*keep

boats.n.ij = Matrix(boat.dat, nrow=N, ncol=N, sparse =T)
diag(boats.n.ij) = 0

boats.n.ij[1:10, 1:10]
#> 10 x 10 sparse Matrix of class "dgCMatrix"
#>                          
#>  [1,] . . . . . . . . . .
#>  [2,] . . . 7 . . . . . .
#>  [3,] . . . . . . 3 . . .
#>  [4,] . . . . . . . . . .
#>  [5,] . . . . . . . . . .
#>  [6,] . . . . . . . . . .
#>  [7,] . . . . . . . . . .
#>  [8,] . . . . . . . 0 . .
#>  [9,] . . . . . . . . . .
#> [10,] . . 2 . . . . . . .

n.ij = N
B = 5

system.time({
  MIPModel() |> 
    add_variable(x[i], type = "binary", i = 1:n.ij) |>
    add_variable(u[i, j], type = "binary", i = 1:n.ij, j = 1:n.ij, boats.n.ij[i, j] > 0) |> 
    set_objective(sum_over(boats.n.ij[i, j] * u[i, j], i = 1:n.ij, j = 1:n.ij, boats.n.ij[i, j] > 0), "max") |>
    add_constraint(u[i, j] <= x[i] + x[j], i = 1:n.ij, j = 1:n.ij, boats.n.ij[i, j] > 0) |>
    add_constraint(sum_over(x[i], i = 1:n.ij) <= B)
})
#>    user  system elapsed 
#>  33.788   0.123  33.985
```

<sup>Created on 2022-01-31 by the [reprex package](https://reprex.tidyverse.org) (v2.0.1)</sup>

**Comment by BajczA475** [comment] 2022-01-31 15:35
It's definitely a lot faster with the updates! Although there must be something amiss with the model specification because I don't get the pattern I would expect in the solution. 

Bobs.mod = MIPModel() %>% 
  add_variable(x[i], type = "binary", i = 1:n.ij) %>% 
  add_variable(y[j], type = "binary", j = 1:n.ij) %>% 
  add_constraint(x[i] == y[j], i = 1:n.ij, j = 1:n.ij, i == j) %>% 
  add_variable(u[i, j], type = "binary", i = 1:n.ij, j = 1:n.ij, boats.n.ij[i,j] > 0) %>%
  set_objective(sum_over(boats.n.ij[i,j] * u[i,j], i=1:n.ij, j=1:n.ij, boats.n.ij[i,j] >0), "max") %>% 
  add_constraint(u[i,j] <= x[i] + y[j], i = 1:n.ij, j = 1:n.ij, boats.n.ij[i,j] > 0) %>% 
  add_constraint(sum_over(x[i], i = 1:n.ij) <= B)

Bobs.mod.solved = Bobs.mod %>% 
  solve_model(with_ROI(solver = "symphony", verbosity = -1, time_limit=60*60*2, gap_limit=1))

testB = get_solution(Bobs.mod.solved, u[i,j])
test2B = tidyr::pivot_wider(testB, names_from = j, values_from = value) %>% dplyr::select(-variable, -i)
test3B = as.matrix(test2B, nrow=n.ij, byrow=T)

lattice:Llevelplot(test3B)

**Comment by dirkschumacher** [comment] 2022-01-31 15:43
Maybe it is that `u[i,j] <= x[i] + y[j]` constraint? The following should work (or at least is equal to the paper I believe):

```R
MIPModel() |> 
    add_variable(x[i], type = "binary", i = 1:n.ij) |>
    add_variable(u[i, j], type = "binary", i = 1:n.ij, j = 1:n.ij, boats.n.ij[i, j] > 0) |> 
    set_objective(sum_over(boats.n.ij[i, j] * u[i, j], i = 1:n.ij, j = 1:n.ij, boats.n.ij[i, j] > 0), "max") |>
    add_constraint(u[i, j] <= x[i] + x[j], i = 1:n.ij, j = 1:n.ij, boats.n.ij[i, j] > 0) |>
    add_constraint(sum_over(x[i], i = 1:n.ij) <= B)
```

If you believe there is a problem in {ompr}, let me know!

**Comment by BajczA475** [comment] 2022-01-31 16:34
I had tried that and got the same output--but it's because I needed to update my plotting code to handle the fact that u's solution was only going to have values for cells where boats_n_ij > 0, so it wasn't going to be of the same dimensions as the original problem. This worked:

Bobs.mod = MIPModel() %>% 
  add_variable(x[i], type = "binary", i = 1:n.ij) %>% 
  add_variable(u[i, j], type = "binary", i = 1:n.ij, j = 1:n.ij, boats.n.ij[i,j] > 0) %>%
  set_objective(sum_over(boats.n.ij[i,j] * u[i,j], i=1:n.ij, j=1:n.ij, boats.n.ij[i,j] >0), "max") %>% 
  add_constraint(u[i,j] <= x[i] + x[j], i = 1:n.ij, j = 1:n.ij, boats.n.ij[i,j] > 0) %>% 
  add_constraint(sum_over(x[i], i = 1:n.ij) <= B)

Bobs.mod.solved = Bobs.mod %>% 
  solve_model(with_ROI(solver = "symphony", verbosity = -1, time_limit=60*60*2, gap_limit=

testB = get_solution(Bobs.mod.solved, u[i,j]) %>% dplyr::select(-variable)
testC = slam::simple_triplet_matrix(i = testB$i, j = testB$j, v = testB$value)
testD = Matrix::Matrix(testC, sparse =T, nrow=N, ncol=N)

lattice::levelplot(as.matrix(testD), col.regions = c("black", "white"))

![Screenshot 2022-01-31 103419](https://user-images.githubusercontent.com/15620636/151834007-203ec20b-b81f-4945-9395-b8c38ddd3399.png)

Thanks for all the help! It's been really great.

**Comment by dirkschumacher** [comment] 2022-01-31 21:34
I close this. Feel free to open again.

**Closed by dirkschumacher** 2022-01-31 21:34 UTC
